config/routes.rb
Rails.application.routes.draw do
  resources :repositories, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
  root to: "repositories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/owner.rb
class Owner < ApplicationRecord
    has_one :repository
end

app/models/repository.rb
class Repository < ApplicationRecord
  belongs_to :owner, dependent: :destroy

  scope :order_by_more_stars, -> { order(stargazers_count: :desc) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_languages
  before_action :set_repository, only: [:show]
  before_action :set_repositories, only: [:index]
  before_action :destroy_all,:fetch_repositories, only: [:search]

  def index
  end

  def show
  end

  def search
    redirect_to repositories_path, notice: "Estamos buscando os repositórios no Github. Aguarde ..."
  end

  private
    def set_languages
      @languages = ['ruby','java','javascript','php','groovy']
    end

    def set_repository
      @repository = Repository.find(params[:id])
    end

    def set_repositories
      @repositories = Repository.includes(:owner).order_by_more_stars
    end

    def destroy_all
      Repository.destroy_all
    end

    def fetch_repositories
      FetchGithubRepositoriesWorker.perform_async(@languages)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def boolean_format(value)
    value ? 'Sim' : 'Não'
  end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubApp</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/repositories/_repositories.html.erb
<% unless repositories.empty? %>
  <table>
    <thead>
      <tr>
        <th>Full name</th>
        <th>Html url</th>
        <th>Owner</th>
        <th>Language</th>
        <th>Stargazers count</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% repositories.each do |repository| %>
        <tr>
          <td><%= repository.full_name %></td>
          <td><%= link_to nil, repository.html_url %></td>
          <td><%= repository.owner.login %></td>
          <td><%= repository.language %></td>
          <td><%= repository.stargazers_count %></td>
          <td><%= link_to 'Show', repository %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/repositories/index.html.erb
<h1>Repositories</h1>

<p>Este app exibe os 10 repositórios mais bem rankeados no Github das seguintes linguagens: <%= @languages.join(', ').titleize %>.</p>

<p id="notice"><%= notice %></p>

<div id="content">
  <%= link_to 'Buscar repositórios', search_repositories_path, id: 'search' %>
  <div id="repositories-grid">
    <%= render partial: 'repositories', locals: { repositories: @repositories } %>
  </div>
</div>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Node:</strong>
  <%= @repository.node_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @repository.name %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @repository.full_name %>
</p>

<p>
  <strong>Private repo:</strong>
  <%= boolean_format(@repository.private_repo) %>
</p>

<p>
  <strong>Html url:</strong>
    <%= link_to nil, @repository.html_url unless @repository.html_url.nil? %>
</p>

<p>
  <strong>Description:</strong>
  <%= @repository.description %>
</p>

<p>
  <strong>Fork:</strong>
  <%= @repository.fork %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to nil, @repository.url unless @repository.url.nil? %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @repository.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @repository.updated_at %>
</p>

<p>
  <strong>Pushed at:</strong>
  <%= @repository.pushed_at %>
</p>

<p>
  <strong>Homepage:</strong>
  <%= link_to nil, @repository.homepage unless @repository.homepage %>
</p>

<p>
  <strong>Size:</strong>
  <%= @repository.size %>
</p>

<p>
  <strong>Stargazers count:</strong>
  <%= @repository.stargazers_count %>
</p>

<p>
  <strong>Watchers count:</strong>
  <%= @repository.watchers_count %>
</p>

<p>
  <strong>Language:</strong>
  <%= @repository.language %>
</p>

<p>
  <strong>Forks count:</strong>
  <%= @repository.forks_count %>
</p>

<p>
  <strong>Open issues count:</strong>
  <%= @repository.open_issues_count %>
</p>

<p>
  <strong>Master branch:</strong>
  <%= @repository.master_branch %>
</p>

<p>
  <strong>Default branch:</strong>
  <%= @repository.default_branch %>
</p>

<p>
  <strong>Score:</strong>
  <%= @repository.score %>
</p>

<h2>Owner</h2>
<p>
  <strong>Node ID:</strong>
  <%= @repository.owner.node_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= image_tag @repository.owner.avatar_url, size: 100 unless @repository.owner.avatar_url.nil? %>
</p>

<p>
  <strong>Login:</strong>
  <%= @repository.owner.login %>
</p>

<p>
  <strong>Html Url:</strong>
  <%= link_to nil, @repository.owner.html_url unless @repository.owner.html_url.nil? %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to nil, @repository.owner.url unless @repository.owner.url.nil? %>
</p>

<%= link_to 'Back', repositories_path %>